name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-west1
  SERVICE_NAME: yenup
  REPO_NAME: yenup

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Google Cloud Auth
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Google Cloud SDK Setup
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Docker Auth
      - name: Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build and Push Container
      - name: Build and Push Container
        run: |
          IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          env_vars: |
            API_PROVIDER=frankfurter
            FRANKFURTER_API_URL=https://api.frankfurter.app/
            BASE_CURRENCY=CAD
            TARGET_CURRENCY=JPY
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}

